//! DLS1 and list commitment bytes shared with Python's v2.1 list reference.

use dcg_disputes as D;
use sha2::Digest;

struct Soft;
impl D::Sha256 for Soft {
    fn hash(&self, parts: &[&[u8]]) -> D::Hash {
        let mut h = sha2::Sha256::new();
        for part in parts {
            h.update(part);
        }
        h.finalize().into()
    }
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn hex_string(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn vectors() -> serde_json::Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/golden/dcg/disputes_v21/lists.json"
    );
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

fn root_of(leaves: &[D::Hash]) -> D::Hash {
    let n = leaves.len().max(1);
    let height = usize::BITS - (n - 1).leading_zeros();
    let mut row = leaves.to_vec();
    row.resize(1 << height, D::empty(&Soft, D::Tree::List, 0));
    for level in 0..height {
        row = row
            .chunks(2)
            .map(|pair| D::node(&Soft, D::Tree::List, level as u16, &pair[0], &pair[1]))
            .collect();
    }
    row[0]
}

#[test]
fn dls1_and_list_digest_match_python_vectors() {
    let v = vectors();
    let raw = hex(v["list_spec"].as_str().unwrap());
    let spec = D::ListSpec(&raw);
    assert!(spec.valid());
    assert_eq!(spec.id(), v["list_id"].as_u64().unwrap() as u32);
    assert_eq!(spec.count(), v["element_refs"].as_array().unwrap().len());
    assert_eq!(raw.len(), 12 + 48 * spec.count());

    let refs: Vec<Vec<u8>> = v["element_refs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| hex(x.as_str().unwrap()))
        .collect();
    let packed: Vec<u8> = refs.iter().flatten().copied().collect();
    let leaves: Vec<D::Hash> = refs
        .iter()
        .enumerate()
        .map(|(j, r)| D::list_leaf(&Soft, j as u32, r).unwrap())
        .collect();
    assert_eq!(
        leaves.iter().map(|h| hex_string(h)).collect::<Vec<_>>(),
        v["list_leaf_hashes"]
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().to_owned())
            .collect::<Vec<_>>()
    );
    assert_eq!(
        root_of(&leaves).as_slice(),
        hex(v["list_tree_root"].as_str().unwrap())
    );
    assert_eq!(
        D::list_digest(&Soft, &packed).unwrap().as_slice(),
        hex(v["list_digest"].as_str().unwrap())
    );
    let refs: Vec<[u8; D::VALUE_REF_BYTES]> = packed
        .chunks_exact(D::VALUE_REF_BYTES)
        .map(|r| r.try_into().unwrap())
        .collect();
    assert_eq!(
        D::list_digest_elements(&Soft, &refs).unwrap().as_slice(),
        hex(v["list_digest"].as_str().unwrap())
    );

    let leaf = hex(v["step_leaf"].as_str().unwrap());
    let parsed = D::parse_leaf(&leaf).unwrap();
    assert_eq!(
        parsed.input(0)[23..55],
        hex(v["list_digest"].as_str().unwrap())
    );
    let edge = hex(v["edge_claim_bodies"]["0"].as_str().unwrap());
    let step = hex(v["step_claim_body"].as_str().unwrap());
    assert_eq!((edge[0], edge[1]), (2, 0));
    assert_eq!((step[0], step[1]), (3, 0));
    let reveal = hex(v["staged_leaf_reveal"].as_str().unwrap());
    assert_eq!(&reveal[..4], b"LVR1");

    // These exact wire bodies are replayed by the program's native/SBF list
    // oracle. The scenario file is independently generated by Python's client.
    let scenarios_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/golden/dcg/disputes_v21/list_scenarios.json"
    );
    let scenarios: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(scenarios_path).unwrap()).unwrap();
    for (scenario, element) in [
        ("mixed-edge-kind1", "0"),
        ("mixed-edge-kind2", "6"),
        ("mixed-edge-kind3", "12"),
    ] {
        let row = scenarios["scenarios"]
            .as_array()
            .unwrap()
            .iter()
            .find(|row| row["name"] == scenario)
            .unwrap();
        assert_eq!(row["claim_body"], v["edge_claim_bodies"][element]);
        assert_eq!(hex(row["claim_body"].as_str().unwrap())[0], 2);
    }
    let step_row = scenarios["scenarios"]
        .as_array()
        .unwrap()
        .iter()
        .find(|row| row["name"] == "mixed-step-honest")
        .unwrap();
    assert_eq!(step_row["claim_body"], v["step_claim_body"]);
}
