#!/usr/bin/env python3
"""Write crates/dcg-program/tests/fixtures/graph_v2_hello.rs: the Hello Graph
blobs the Python client uploads (canonical DCGG/DCPL and the step table) for
the native graph-v2 program tests. Re-run after any lowering change."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))
from dcg import tracing  # noqa: E402
from dcg.kernels import add_i32, identity_i32  # noqa: E402


def hello(a, b):
    with tracing.region("child"):
        total = add_i32(a, b)
    return identity_i32(total)


def rs(name: str, data: bytes) -> str:
    body = ", ".join(str(b) for b in data)
    return f"pub const {name}: &[u8] = &[{body}];\n"


g = tracing.trace(hello)
out = ["// Generated by scripts/graph_v2_test_fixture.py; do not edit.\n"]
for mode in ("optimistic", "consensus"):
    tag = mode.upper()
    graph, plan = g.graph_bytes(mode), g.plan_bytes(mode)
    out += [rs(f"GRAPH_{tag}", graph), rs(f"PLAN_{tag}", plan), rs(f"MANIFEST_{tag}", plan[104:136])]
out.append(rs("STEP_TABLE", g.step_table()))
path = ROOT / "crates/dcg-program/tests/fixtures/graph_v2_hello.rs"
path.write_text("".join(out))
print(path, path.stat().st_size)
